/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CompeticoesRouteImport } from './routes/competicoes'
import { Route as ComunidadeRouteImport } from './routes/comunidade'
import { Route as ContatoRouteImport } from './routes/contato'
import { Route as DiarioRouteImport } from './routes/diario'
import { Route as EngenhariaRouteImport } from './routes/engenharia'
import { Route as EquipeRouteImport } from './routes/equipe'
import { Route as GaleriaRouteImport } from './routes/galeria'
import { Route as MecaAiRouteImport } from './routes/meca-ai'
import { Route as ParceirosRouteImport } from './routes/parceiros'
import { Route as ProjetosRouteImport } from './routes/projetos'
import { Route as RoboRouteImport } from './routes/robo'
import { Route as TemporadaRouteImport } from './routes/temporada'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CompeticoesRoute = CompeticoesRouteImport.update({
  id: '/competicoes',
  path: '/competicoes',
  getParentRoute: () => rootRouteImport,
} as any)
const ComunidadeRoute = ComunidadeRouteImport.update({
  id: '/comunidade',
  path: '/comunidade',
  getParentRoute: () => rootRouteImport,
} as any)
const ContatoRoute = ContatoRouteImport.update({
  id: '/contato',
  path: '/contato',
  getParentRoute: () => rootRouteImport,
} as any)
const DiarioRoute = DiarioRouteImport.update({
  id: '/diario',
  path: '/diario',
  getParentRoute: () => rootRouteImport,
} as any)
const EngenhariaRoute = EngenhariaRouteImport.update({
  id: '/engenharia',
  path: '/engenharia',
  getParentRoute: () => rootRouteImport,
} as any)
const EquipeRoute = EquipeRouteImport.update({
  id: '/equipe',
  path: '/equipe',
  getParentRoute: () => rootRouteImport,
} as any)
const GaleriaRoute = GaleriaRouteImport.update({
  id: '/galeria',
  path: '/galeria',
  getParentRoute: () => rootRouteImport,
} as any)
const MecaAiRoute = MecaAiRouteImport.update({
  id: '/meca-ai',
  path: '/meca-ai',
  getParentRoute: () => rootRouteImport,
} as any)
const ParceirosRoute = ParceirosRouteImport.update({
  id: '/parceiros',
  path: '/parceiros',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjetosRoute = ProjetosRouteImport.update({
  id: '/projetos',
  path: '/projetos',
  getParentRoute: () => rootRouteImport,
} as any)
const RoboRoute = RoboRouteImport.update({
  id: '/robo',
  path: '/robo',
  getParentRoute: () => rootRouteImport,
} as any)
const TemporadaRoute = TemporadaRouteImport.update({
  id: '/temporada',
  path: '/temporada',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/competicoes': typeof CompeticoesRoute
  '/comunidade': typeof ComunidadeRoute
  '/contato': typeof ContatoRoute
  '/diario': typeof DiarioRoute
  '/engenharia': typeof EngenhariaRoute
  '/equipe': typeof EquipeRoute
  '/galeria': typeof GaleriaRoute
  '/meca-ai': typeof MecaAiRoute
  '/parceiros': typeof ParceirosRoute
  '/projetos': typeof ProjetosRoute
  '/robo': typeof RoboRoute
  '/temporada': typeof TemporadaRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/competicoes': typeof CompeticoesRoute
  '/comunidade': typeof ComunidadeRoute
  '/contato': typeof ContatoRoute
  '/diario': typeof DiarioRoute
  '/engenharia': typeof EngenhariaRoute
  '/equipe': typeof EquipeRoute
  '/galeria': typeof GaleriaRoute
  '/meca-ai': typeof MecaAiRoute
  '/parceiros': typeof ParceirosRoute
  '/projetos': typeof ProjetosRoute
  '/robo': typeof RoboRoute
  '/temporada': typeof TemporadaRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/competicoes': typeof CompeticoesRoute
  '/comunidade': typeof ComunidadeRoute
  '/contato': typeof ContatoRoute
  '/diario': typeof DiarioRoute
  '/engenharia': typeof EngenhariaRoute
  '/equipe': typeof EquipeRoute
  '/galeria': typeof GaleriaRoute
  '/meca-ai': typeof MecaAiRoute
  '/parceiros': typeof ParceirosRoute
  '/projetos': typeof ProjetosRoute
  '/robo': typeof RoboRoute
  '/temporada': typeof TemporadaRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/competicoes'
    | '/comunidade'
    | '/contato'
    | '/diario'
    | '/engenharia'
    | '/equipe'
    | '/galeria'
    | '/meca-ai'
    | '/parceiros'
    | '/projetos'
    | '/robo'
    | '/temporada'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/competicoes'
    | '/comunidade'
    | '/contato'
    | '/diario'
    | '/engenharia'
    | '/equipe'
    | '/galeria'
    | '/meca-ai'
    | '/parceiros'
    | '/projetos'
    | '/robo'
    | '/temporada'
  id:
    | '__root__'
    | '/'
    | '/competicoes'
    | '/comunidade'
    | '/contato'
    | '/diario'
    | '/engenharia'
    | '/equipe'
    | '/galeria'
    | '/meca-ai'
    | '/parceiros'
    | '/projetos'
    | '/robo'
    | '/temporada'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CompeticoesRoute: typeof CompeticoesRoute
  ComunidadeRoute: typeof ComunidadeRoute
  ContatoRoute: typeof ContatoRoute
  DiarioRoute: typeof DiarioRoute
  EngenhariaRoute: typeof EngenhariaRoute
  EquipeRoute: typeof EquipeRoute
  GaleriaRoute: typeof GaleriaRoute
  MecaAiRoute: typeof MecaAiRoute
  ParceirosRoute: typeof ParceirosRoute
  ProjetosRoute: typeof ProjetosRoute
  RoboRoute: typeof RoboRoute
  TemporadaRoute: typeof TemporadaRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/competicoes': {
      id: '/competicoes'
      path: '/competicoes'
      fullPath: '/competicoes'
      preLoaderRoute: typeof CompeticoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/comunidade': {
      id: '/comunidade'
      path: '/comunidade'
      fullPath: '/comunidade'
      preLoaderRoute: typeof ComunidadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contato': {
      id: '/contato'
      path: '/contato'
      fullPath: '/contato'
      preLoaderRoute: typeof ContatoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/diario': {
      id: '/diario'
      path: '/diario'
      fullPath: '/diario'
      preLoaderRoute: typeof DiarioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/engenharia': {
      id: '/engenharia'
      path: '/engenharia'
      fullPath: '/engenharia'
      preLoaderRoute: typeof EngenhariaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/equipe': {
      id: '/equipe'
      path: '/equipe'
      fullPath: '/equipe'
      preLoaderRoute: typeof EquipeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/galeria': {
      id: '/galeria'
      path: '/galeria'
      fullPath: '/galeria'
      preLoaderRoute: typeof GaleriaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/meca-ai': {
      id: '/meca-ai'
      path: '/meca-ai'
      fullPath: '/meca-ai'
      preLoaderRoute: typeof MecaAiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parceiros': {
      id: '/parceiros'
      path: '/parceiros'
      fullPath: '/parceiros'
      preLoaderRoute: typeof ParceirosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projetos': {
      id: '/projetos'
      path: '/projetos'
      fullPath: '/projetos'
      preLoaderRoute: typeof ProjetosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robo': {
      id: '/robo'
      path: '/robo'
      fullPath: '/robo'
      preLoaderRoute: typeof RoboRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/temporada': {
      id: '/temporada'
      path: '/temporada'
      fullPath: '/temporada'
      preLoaderRoute: typeof TemporadaRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CompeticoesRoute: CompeticoesRoute,
  ComunidadeRoute: ComunidadeRoute,
  ContatoRoute: ContatoRoute,
  DiarioRoute: DiarioRoute,
  EngenhariaRoute: EngenhariaRoute,
  EquipeRoute: EquipeRoute,
  GaleriaRoute: GaleriaRoute,
  MecaAiRoute: MecaAiRoute,
  ParceirosRoute: ParceirosRoute,
  ProjetosRoute: ProjetosRoute,
  RoboRoute: RoboRoute,
  TemporadaRoute: TemporadaRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
